#!/usr/bin/bash

sudo medium_setup
sudo rm -f /usr/local/bin/medium_setup

gsettings set org.gnome.desktop.interface font-name 'Sans 10'
gsettings set org.gnome.desktop.interface document-font-name 'Serif 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false
gnome-extensions enable 'appindicatorsupport@rgcjonas.gmail.com'

cp -r /opt/configs/backgrounds/ $XDG_DATA_HOME
cp -r /opt/configs/user/ghostty $XDG_CONFIG_HOME
cp -r /opt/configs/user/firefox/* $XDG_CONFIG_HOME/mozilla/firefox/*.default-release/

git clone --depth 1 'https://aur.archlinux.org/yay-bin.git' /tmp/yay-bin
makepkg -sicD /tmp/yay-bin

yay -Syu intel-compute-runtime-legacy-bin

sudo rm -fr /opt/configs
sudo rm -f /usr/local/bin/medium_user
