#!/usr/bin/bash

sed -i -e '/^#en_US.UTF-8/s/^#//' -e '/^#ar_EG.UTF-8/s/^#//' /etc/locale.gen
locale-gen
printf '%s\n' 'LANG=en_US.UTF-8' | tee /etc/locale.conf

ln -f -s /usr/share/zoneinfo/Asia/Riyadh /etc/localtime
hwclock -u -w

printf '%s\n%s\n' 'KEYMAP=us' 'FONT=default8x16' | tee /etc/vconsole.conf
printf '%s\n' 'aeiedamo' | tee /etc/hostname

sed -i -e '/^#NoExtract/s/$/ boot\/intel-ucode.img/' -e '/^#NoExtract/s/^#// ' -e '/^#Color/s/^#//' -e '/^#Verbose/s/^#//' -e '/^#\[core-testing\]\|^#\[extra-testing\]/,+1s/^#//' /etc/pacman.conf
printf '%s\n' 'Server = https://mirror.pkgbuild.com/$repo/os/$arch' | tee /etc/pacman.d/mirrorlist
sed -i -e 's/^MAKEFLAGS.*/MAKEFLAGS="-j8"/' -e '/^#BUILDDIR/s/^#//' -e '/^OPTIONS/s/debug/!&/' /etc/makepkg.conf

pacman -Syu --needed linux linux-headers apparmor base-devel bash-completion devtools dosfstools edk2-shell efibootmgr fwupd intel-ucode linux-firmware linux-tools-meta man-db mkinitcpio nvme-cli snap-pac wireless-regdb

sed -i -e '/^HOOKS/s/keymap/plymouth/' /etc/mkinitcpio.conf

sed -i -e '/SA/s/^#//' /etc/conf.d/wireless-regdom

bootctl install --variables=no

printf '%s\t%s\n%s\t%s\n%s\t%s\n%s\t%s%s %s %s %s\n' 'title' 'Arch Linux' 'linux' '/vmlinuz-linux' 'initrd' '/initramfs-linux.img' 'options' 'root=UUID=' "$(lsblk -dno UUID /dev/sda2)" 'rw rootflags=compress=zstd,subvol=/@' 'lsm=landlock,lockdown,yama,integrity,apparmor,bpf' 'quiet splash' | tee /boot/loader/entries/arch-linux.conf

printf '%s\t%s\n' 'default' 'arch-linux.conf' | tee /boot/loader/loader.conf

pacman -Syu --needed gdm gnome-control-center 7zip alsa-firmware alsa-utils baobab cdrtools dconf-editor evolution-data-server file-roller gnome-browser-connector gnome-characters gnome-keyring gnome-remote-desktop gnome-shell-extension-appindicator gnome-software gnome-themes-extra gnome-tweaks gnome-user-share gst-plugin-va gst-plugins-bad gst-plugins-ugly guestfs-tools gvfs-afc gvfs-google gvfs-onedrive gvfs-gphoto2 gvfs-mtp gvfs-nfs intel-media-sdk libappindicator libayatana-appindicator loupe malcontent mission-center modemmanager networkmanager noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra orca papers pipewire-alsa pipewire-jack plymouth podman proton-vpn-gtk-app qemu-full qemu-user-static-binfmt rygel snapshot sof-firmware system-config-printer throttled ttf-noto-nerd tuned-ppd virt-manager vulkan-intel unrar usb_modeswitch zip zram-generator

pacman -Syu --needed ardour arch-wiki-docs bluez-cups bluez-utils calf cronie crun cups-pdf distrobox dnsmasq easyeffects fastfetch firefox firewall-applet ghostty gimp github-cli gparted hunspell-en_us inetutils iotas lazygit libreoffice-fresh lsp-plugins-lv2 mda.lv2 mpv net-tools obs-studio onnxruntime-cpu qalculate-gtk qbittorrent qt6-multimedia-gstreamer radvd rnote rust swtpm telegram-desktop thunderbird trash-cli wl-clipboard yt-dlp zam-plugins-lv2 zed

systemctl enable apparmor bluetooth cronie cups firewalld fwupd-refresh.timer gdm gnome-remote-desktop libvirtd ModemManager NetworkManager sshd systemd-boot-update systemd-resolved systemd-timesyncd throttled tuned tuned-ppd virtnetworkd virtqemud virtstoraged

cp /usr/share/edk2-shell/x64/Shell.efi /boot/shellx64.efi

printf '%s\n' '%wheel ALL=(ALL:ALL) ALL' | tee /etc/sudoers.d/01-wheel

passwd -d -l root

useradd -c 'AlaEldin Mohamed' -G audio,disk,kvm,libvirt,log,storage,wheel -m am
passwd am

printf '%s\n' 'options psmouse synaptics_intertouch=1' | tee /etc/modprobe.d/psmouse.conf

printf '%s\n%s\n%s\n' '[zram0]' 'zram-size=ram' 'compression-algorithm=zstd' | tee /etc/systemd/zram-generator.conf

printf '%s\n' 'ListenAddress aeiedamo.local' | tee /etc/ssh/sshd_config.d/00-local.conf

printf '%s\n' 'export EDITOR=vim VISUAL=vim' | tee /etc/profile.d/01-editor.sh

printf '%s\n' 'export XDG_CONFIG_HOME="$HOME/.config"' | tee /etc/profile.d/02-xdg.sh

printf '%s\n' 'export XDG_DATA_DIRS="${XDG_DATA_DIRS}:/var/lib/flatpak/exports/share:${HOME}/.local/share/flatpak/exports/share"' | tee /etc/profile.d/03-flatpak.sh

mv /opt/configs/systemd/logind.conf.d /etc/systemd/

mv /opt/configs/fonts/local.conf /etc/fonts/

mv /opt/configs/gdm/gdm /etc/dconf/profile/
mv /opt/configs/gdm/gdm.d /etc/dconf/db/
dconf update
