#!/usr/bin/bash

DISK1="$(realpath /dev/disk/by-id/nvme-nvme.1e4b-30303335363230303030303532-4e452d3154422032323432-00000001)"
DISK2="$(realpath /dev/disk/by-id/nvme-eui.e8238fa6bf530001001b448b47f32f0c)"
BOOT="${DISK1}p1"
CRPTP1="${DISK1}p2"
CRPTP2="${DISK2}p1"
ROOTP1='rootp1'
ROOTP2='rootp2'

nvme format /dev/nvme0 -f -n 1 -l 0 -s 1 -r
nvme format /dev/nvme1 -f -n 1 -l 0 -s 1 -r
partprobe $DISK1 $DISK2

sgdisk -n 1:0:+1G -c 1:'BOOT' -t 1:ef00 -n 2:0:0 -c 2:'ROOT' -t 2:8304 $DISK1
sgdisk -n 1:0:0 -c 1:'ROOT' -t 1:8304 $DISK2

mkfs.fat -F 32 -n 'BOOT' $BOOT

cryptsetup luksFormat --label 'CRPT' -q $CRPTP1
cryptsetup --allow-discards --persistent open $CRPTP1 $ROOTP1

cryptsetup luksFormat --label 'CRPT' -q $CRPTP2
cryptsetup --allow-discards --persistent open $CRPTP2 $ROOTP2

mkfs.btrfs -L 'ROOT' -d raid0 -m raid0 /dev/mapper/$ROOTP1 /dev/mapper/$ROOTP2
mount -o compress=zstd /dev/mapper/$ROOTP1 /mnt
btrfs subvolume create /mnt/@ /mnt/@home /mnt/@var /mnt/@snapshots
umount /mnt
mount -o compress=zstd,subvol=/@ /dev/mapper/$ROOTP1 /mnt
mount -m -o compress=zstd,subvol=/@home /dev/mapper/$ROOTP1 /mnt/home
mount -m -o compress=zstd,subvol=/@var /dev/mapper/$ROOTP1 /mnt/var
mount -m -o compress=zstd,subvol=/@snapshots /dev/mapper/$ROOTP1 /mnt/.snapshots
mount -m -o nosuid,nodev,noexec,nosymfollow,fmask=0177,dmask=0077 $BOOT /mnt/boot

pacstrap -KM /mnt base iptables

genfstab -U /mnt | tee -a /mnt/etc/fstab

install -m 0755 ./oobeinstall /mnt/usr/local/bin/

arch-chroot -S /mnt /usr/local/bin/oobeinstall
rm -f /mnt/usr/local/bin/oobeinstall

install -m 0755 ./oobepostinstall /mnt/usr/local/bin/
install -m 0755 -o am ./oobeuser /mnt/usr/local/bin/

systemctl reboot --firmware-setup
