#!/usr/bin/bash

CNTR1='/dev/nvme0'
CNTR2='/dev/nvme1'
DISK1="${CNTR1}n1"
DISK2="${CNTR2}n1"
BOOT="${DISK1}p1"
CRPTP1="${DISK1}p2"
CRPTP2="${DISK2}p1"
ROOTP1='rootp1'
ROOTP2='rootp2'


pacman -Syu
rm -fr /var/cache/pacman/pkg/download-*
pacman -Scc

nvme format $CNTR1 -f -n 1 -l 0 -s 1 -r
nvme format $CNTR2 -f -n 1 -l 0 -s 1 -r
partprobe $DISK1 $DISK2

sgdisk -n 1:0:+1G -c 1:'BOOT' -t 1:ef00 -n 2:0:0 -c 2:'ROOT' -t 2:8304 $DISK1
sgdisk -n 1:0:0 -c 1:'ROOT' -t 1:8304 $DISK2

mkfs.fat -F 32 -n 'BOOT' $BOOT

cryptsetup luksFormat --label 'CRPT' -q $CRPTP1
cryptsetup --allow-discards --persistent open $CRPTP1 $ROOTP1

cryptsetup luksFormat --label 'CRPT' -q $CRPTP2
cryptsetup --allow-discards --persistent open $CRPTP2 $ROOTP2

mkfs.btrfs -L 'ROOT' -m single /dev/mapper/$ROOTP1 /dev/mapper/$ROOTP2
mount -o compress=zstd /dev/mapper/$ROOTP1 /mnt
btrfs subvolume create /mnt/@ /mnt/@home /mnt/@var /mnt/@snapshots
umount /mnt
mount -o compress=zstd,subvol=/@ /dev/mapper/$ROOTP1 /mnt
mount -m -o compress=zstd,subvol=/@home /dev/mapper/$ROOTP1 /mnt/home
mount -m -o compress=zstd,subvol=/@var /dev/mapper/$ROOTP1 /mnt/var
mount -m -o compress=zstd,subvol=/@snapshots /dev/mapper/$ROOTP1 /mnt/.snapshots
mount -m -o nosuid,nodev,noexec,nosymfollow,fmask=0177,dmask=0077 $BOOT /mnt/efi

pacstrap -iKM /mnt

genfstab -U /mnt | tee -a /mnt/etc/fstab

cp ./oobe-install /mnt/usr/local/bin/
arch-chroot -S /mnt /usr/local/bin/oobe-install
rm -f /mnt/usr/local/bin/oobe-install

cp ./oobe-postinstall /mnt/usr/local/bin/
