#!/usr/bin/bash

DISK="/dev/sda"
BOOT="${DISK1}1"
CRPT="${DISK1}2"
ROOT='root'

blkdiscard -fz $DISK
partprobe $DISK

sgdisk -n 1:0:+1G -c 1:'BOOT' -t 1:ef00 -n 2:0:0 -c 2:'ROOT' -t 2:8304 $DISK

mkfs.fat -F 32 -n 'BOOT' $BOOT

cryptsetup luksFormat --label 'CRPT' -q $CRPT
cryptsetup --allow-discards --persistent open $CRPT $ROOT

mkfs.btrfs -L 'ROOT' -d single -m single /dev/mapper/$ROOT
mount -o compress=zstd /dev/mapper/$ROOT /mnt
btrfs subvolume create /mnt/@ /mnt/@home /mnt/@var /mnt/@snapshots
umount /mnt
mount -o compress=zstd,subvol=/@ /dev/mapper/$ROOT /mnt
mount -m -o compress=zstd,subvol=/@home /dev/mapper/$ROOT /mnt/home
mount -m -o compress=zstd,subvol=/@var /dev/mapper/$ROOT /mnt/var
mount -m -o compress=zstd,subvol=/@snapshots /dev/mapper/$ROOT /mnt/.snapshots
mount -m -o nosuid,nodev,noexec,nosymfollow,fmask=0177,dmask=0077 $BOOT /mnt/boot

pacstrap -KM /mnt base iptables

genfstab -U /mnt | tee -a /mnt/etc/fstab

install -m 0700 -p ./oobeinstalltmp /mnt/usr/local/bin/

arch-chroot -S /mnt /usr/local/bin/oobeinstalltmp
rm -f /mnt/usr/local/bin/oobeinstalltmp

install -m 0755 -p ./oobepostinstalltmp /mnt/usr/local/bin/
install -m 0755 -p ./oobeusertmp /mnt/usr/local/bin/

systemctl reboot --firmware-setup
