#!/usr/bin/bash

DISK="/dev/sda"
BOOT="${DISK}1"
CRPT="${DISK}2"
ROOT='root'

rm -fr /boot/EFI

bootctl remove

sed -i -e '/^default_uki/s/Linux\/arch-linux.efi/BOOT\/BOOTX64.EFI/' /etc/mkinitcpio.d/linux.preset

mkinitcpio -P

systemd-cryptenroll --tpm2-device /dev/tpmrm0 --tpm2-public-key /etc/systemd/tpm2-pcr-public-key.pem --tpm2-public-key-pcrs 11 --tpm2-pcrs 7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000 $CRPT

sbsign --key /etc/kernel/secure-boot-private-key.pem --cert /etc/kernel/secure-boot-certificate.pem /usr/lib/fwupd/efi/fwupdx64.efi

cd /tmp

git clone --depth=1 'https://github.com/aeiedamo/configs'

mv ./configs/systemd/logind.conf.d /etc/systemd/
mv ./configs/fonts/local.conf /etc/fonts/
mv ./configs/profile/* /etc/profile.d/
mv ./configs/fwupd/fwupd.conf /etc/fwupd/
mv ./configs/gdm/gdm /etc/dconf/profile/
mv ./configs/gdm/gdm.d /etc/dconf/db/
dconf update

umount /.snapshots
rm -fr /.snapshots
snapper -c root create-config /
snapper -c root set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
snapper -c home create-config /home
snapper -c home set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
btrfs subvolume delete /.snapshots
mkdir /.snapshots
mount -a
systemctl enable snapper-boot.timer snapper-cleanup.timer
