#!/usr/bin/bash

sudo oobepostinstall
sudo rm -f /usr/local/bin/oobepostinstall

gsettings set org.gnome.desktop.interface font-name 'Sans 10'
gsettings set org.gnome.desktop.interface document-font-name 'Serif 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false

cp /opt/configs/user/ghostty $XDG_CONFIG_HOME/ghostty/config
cp -r /opt/configs/user/firefox/* $XDG_CONFIG_HOME/mozilla/firefox/*.default-release/

sudo rm -fr /opt/configs

git clone --depth 1 'https://aur.archlinux.org/yay-bin.git' /tmp/yay-bin
makepkg -sicD /tmp/yay-bin

yay -Syu intel-compute-runtime-legacy-bin

sudo rm -f /usr/local/bin/oobeuser
