#!/usr/bin/bash

cd /tmp

gsettings set org.gnome.desktop.interface font-name 'Sans 10'
gsettings set org.gnome.desktop.interface document-font-name 'Serif 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false

firefox &
install -o am ./configs/user/firefox/* $XDG_CONFIG_HOME/mozilla/firefox/*.default-release/
install -o am ./configs/user/ghostty $XDG_CONFIG_HOME/ghostty/config

git clone --depth 1 'https://aur.archlinux.org/yay-bin.git'
cd ./yay-bin
makepkg -sic

sudo rm -f /usr/local/bin/oobe-postinstall
