#!/usr/bin/bash

DISK1="$(realpath /dev/disk/by-id/nvme-nvme.1e4b-30303335363230303030303532-4e452d3154422032323432-00000001)"
DISK2="$(realpath /dev/disk/by-id/nvme-eui.e8238fa6bf530001001b448b47f32f0c)"
BOOT="${DISK1}p1"
CRPTP1="${DISK1}p2"
CRPTP2="${DISK2}p1"
ROOTP1='rootp1'
ROOTP2='rootp2'

ln -fs /usr/share/zoneinfo/Asia/Riyadh /etc/localtime
hwclock -uw

sed -i -e '/^#en_US.UTF-8/s/^#//' -e '/^#ar_EG.UTF-8/s/^#//' /etc/locale.gen
locale-gen
printf 'LANG=en_US.UTF-8\n' | tee /etc/locale.conf

printf 'KEYMAP=us\nFONT=default8x16\n' | tee /etc/vconsole.conf
printf 'aeiedamo\n' | tee /etc/hostname

printf "$ROOTP1\tUUID=$(lsblk -dno UUID $CRPTP1)\tnone\ttpm2-device=/dev/tpmrm0,tpm2-measure-pcr=yes\n$ROOTP2\tUUID=$(lsblk -dno UUID $CRPTP2)\tnone\ttpm2-device=auto,tpm2-measure-pcr=yes\n" | tee /etc/crypttab.initramfs

sed -i -e '/^#NoExtract/s/^#// ' -e '/^NoExtract/s/$/ boot\/intel-ucode.img/' -e '/^#Color/s/^#//' -e '/^#Verbose/s/^#//' -e '/^#\[core-testing\]\|^#\[extra-testing\]/,+1s/^#//' /etc/pacman.conf
printf '%s\n' 'Server = https://mirror.pkgbuild.com/$repo/os/$arch' | tee /etc/pacman.d/mirrorlist
sed -i -e 's/^MAKEFLAGS.*/MAKEFLAGS="-j8"/' -e '/^#BUILDDIR/s/^#//' -e '/^OPTIONS/s/debug/!debug/' /etc/makepkg.conf

pacman -Syu linux linux-headers apparmor base-devel bash-completion devtools dosfstools edk2-shell efibootmgr fwupd intel-ucode linux-firmware linux-tools-meta man-db mkinitcpio nvme-cli sbctl snap-pac wireless-regdb

sed -i -e '/^HOOKS/s/systemd/& btrfs/' -e '/^HOOKS/s/keymap/plymouth/' -e '/^HOOKS/s/filesystems/sd-encrypt &/' /etc/mkinitcpio.conf

sed -i -e '/SA/s/^#//' /etc/conf.d/wireless-regdom

sbctl create-keys

sbctl enroll-keys

sbctl sign -s -o /usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed /usr/lib/systemd/boot/efi/systemd-bootx64.efi

bootctl install

printf "title\tArch Linux\nlinux\t/vmlinuz-linux\ninitrd\t/initramfs-linux.img\noptions\troot=UUID=$(lsblk -dno UUID /dev/mapper/$ROOTP1) rw rootflags=compress=zstd,subvol=/@ lsm=landlock,lockdown,yama,integrity,apparmor,bpf quiet splash\n" | tee /boot/loader/entries/arch-linux.conf

printf 'default\tarch-linux.conf\n' | tee /boot/loader/loader.conf

pacman -Syu gdm gnome-control-center alsa-firmware alsa-utils archlinux-appstream-data dconf-editor evolution-data-server file-roller gnome-browser-connector gnome-characters gnome-keyring gnome-packagekit gnome-remote-desktop gnome-shell-extension-appindicator gnome-themes-extra gnome-user-share gst-plugin-va gst-plugins-bad gst-plugins-ugly guestfs-tools gvfs-afc gvfs-google gvfs-onedrive gvfs-gphoto2 gvfs-mtp gvfs-nfs intel-media-sdk libappindicator libayatana-appindicator malcontent networkmanager noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra orca pipewire-alsa pipewire-jack plymouth proton-vpn-gtk-app qemu-full qemu-user-static-binfmt rygel snapshot sof-firmware system-config-printer ttf-noto-nerd tuned-ppd virt-manager vulkan-intel zram-generator

pacman -Syu ardour arch-wiki-docs baobab bluez-cups bluez-utils calf cronie cups-pdf dnsmasq easyeffects evince fastfetch firefox firewall-applet ghostty gimp github-cli gnome-software gparted hunspell-en_us inetutils lazygit libreoffice-fresh loupe lsp-plugins-lv2 mda.lv2 mission-center mpv net-tools obsidian obs-studio onnxruntime-cpu qalculate-gtk qbittorrent qt6-multimedia-gstreamer radvd rnote rustup swtpm telegram-desktop throttled thunderbird trash-cli wl-clipboard yt-dlp zam-plugins-lv2 zed

systemctl enable apparmor bluetooth cronie cups firewalld fstrim.timer fwupd-refresh.timer gdm gnome-remote-desktop libvirtd NetworkManager sshd systemd-boot-update systemd-resolved systemd-timesyncd throttled tuned tuned-ppd virtnetworkd virtqemud virtstoraged

printf '%s\n' '%wheel ALL=(ALL:ALL) ALL' | tee /etc/sudoers.d/01-wheel

passwd -dl root

useradd -c 'AlaEldin Mohamed' -G audio,disk,kvm,libvirt,log,storage,wheel -m am
passwd am

printf 'options psmouse synaptics_intertouch=1\n' | tee /etc/modprobe.d/psmouse.conf

printf '[zram0]\nzram-size=ram\ncompression-algorithm=zstd\n' | tee /etc/systemd/zram-generator.conf

printf 'ListenAddress aeiedamo.local\n' | tee /etc/ssh/sshd_config.d/00-local.conf

printf "export EDITOR='vim' VISUAL='vim'\n" | tee /etc/profile.d/01-editor.sh

printf '%s\n' 'export XDG_CONFIG_HOME="$HOME/.config"' | tee /etc/profile.d/02-xdg.sh

history -c
