#!/usr/bin/bash

sudo perfect_setup
sudo rm -f /usr/local/bin/perfect_setup

gsettings set org.gnome.desktop.interface font-name 'Sans 10'
gsettings set org.gnome.desktop.interface document-font-name 'Serif 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false
curl -L -o "${XDG_DATA_HOME}/backgrounds/default.jpg" -R -s 'https://unsplash.com/photos/pJ-mNWCg4qo/download?force=true&w=1920'
gsettings set org.gnome.desktop.background picture-uri "file://${XDG_DATA_HOME}/backgrounds/default.jpg"
gsettings set org.gnome.desktop.background picture-uri-dark "file://${XDG_DATA_HOME}/backgrounds/default.jpg"
gsettings set org.gnome.SessionManager logout-prompt false
gnome-extensions enable 'appindicatorsupport@rgcjonas.gmail.com'

printf '%s\n%s\n%s\n%s\n' 'font-family=monospace' 'font-size=10' 'theme=Gruvbox Material Light' 'fullscreen=true' | tee -a ${XDG_CONFIG_HOME}/ghostty/config

ssh-keygen
gpg --full-gen-key
GPGKEY="$(gpg -K --keyid-format long | grep 'sec' | cut -d '/' -f2 | cut -d ' ' -f1)"
gpg -a -o "$HOME/.gnupg/public-keys.d/am.asc" --export ${GPGKEY}

git config set --global user.name 'AlaEldin Mohamed'
git config set --global user.email 'aeiedamo@gmail.com'
git config set --global init.defaultBranch 'main'
git config set --global user.signingkey ${GPGKEY}
git config set --global commit.gpgsign true
git config set --global tag.gpgSign true

git clone --depth 1 'https://aur.archlinux.org/yay-bin.git' /tmp/yay-bin
makepkg -sicD /tmp/yay-bin

yay -Syu intel-compute-runtime-legacy-bin

sudo rm -f /usr/local/bin/perfect_user
