#!/usr/bin/bash

umount /.snapshots
rm -fr /.snapshots
snapper -c root create-config /
snapper -c root set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
snapper -c home create-config /home
snapper -c home set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
btrfs subvolume delete /.snapshots
mkdir /.snapshots
mount -a
systemctl enable snapper-boot.timer snapper-cleanup.timer

git clone --depth 1 'https://github.com/aeiedamo/configs' /tmp/configs

mv /tmp/configs/systemd/logind.conf.d /etc/systemd/
mv /tmp/configs/fonts/local.conf /etc/fonts/
mv /tmp/configs/profile/* /etc/profile.d/
mv /tmp/configs/fwupd/fwupd.conf /etc/fwupd/
mv /tmp/configs/gdm/gdm /etc/dconf/profile/
mv /tmp/configs/gdm/gdm.d /etc/dconf/db/
dconf update
cp /tmp/configs/user/ghostty $XDG_CONFIG_HOME/ghostty/config
cp -r /tmp/configs/user/firefox/* $XDG_CONFIG_HOME/mozilla/firefox/*.default-release/

gsettings set org.gnome.desktop.interface font-name 'Sans 10'
gsettings set org.gnome.desktop.interface document-font-name 'Serif 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false
