#!/usr/bin/bash

sudo rescuepostinstall
sudo rm -f /usr/local/bin/rescuepostinstall

gsettings set org.gnome.desktop.interface font-name 'Sans 10'
gsettings set org.gnome.desktop.interface document-font-name 'Serif 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false

cp /tmp/configs/user/ghostty $XDG_CONFIG_HOME/ghostty/config
firefox &
cp -r /tmp/configs/user/firefox/* $XDG_CONFIG_HOME/mozilla/firefox/*.default-release/
