#!/usr/bin/bash

if [ -z $1 ]; then
	echo "You forgot the device name!"
	exit 1
fi

if [ -z $2 ]; then
	echo "You forgot the iso path!"
	exit 1
fi

DISK="$1"
ISO="$2"
LABEL="$(isoinfo -d -i ${ISO} 2>/dev/null | grep '^Volume id' | cut -d ' ' -f 3)"

blkdiscard -f -z ${DISK}

sgdisk -I -n 1:0:+1G -t 1:0700 -c 1:'BOOT' -N 2 -t 2:0700 -c 2:"${LABEL}" ${DISK}

mkfs.fat -n 'BOOT' "${DISK}1"
mkntfs -L "${LABEL}" -Q "${DISK}2"

mkdir -p /mnt/iso
mount -r ${ISO} /mnt/iso

mkdir -p /mnt/usb/boot /mnt/usb/install
mount "${DISK}1" /mnt/usb/boot
mount "${DISK}2" /mnt/usb/install
mkdir -p /mnt/usb/boot/sources

cp /mnt/iso/* /mnt/usb/boot 2>/dev/null
cp -r /mnt/iso/boot /mnt/usb/boot
cp -r /mnt/iso/efi /mnt/usb/boot
cp -r /mnt/iso/support /mnt/usb/boot
cp /mnt/iso/sources/boot.wim /mnt/usb/boot/sources/

cp -a -T /mnt/iso /mnt/usb/install

sync

umount /mnt/iso /mnt/usb/boot /mnt/usb/install
rm -f -r /mnt/iso /mnt/usb/
